#!/usr/bin/env python3
"""Generate a real ECDSA-P256 update-signature vector for tests/host/test_dfu.c.

Not run by tests/host/run.sh. It produced the constants pasted into that suite,
and it lives here so they can be regenerated and audited rather than taken on
trust -- the same arrangement as gen_pase_vector.py:

    python3 tests/host/gen_dfu_vector.py

WHY A VECTOR AND NOT A LIVE CHECK. dfu_receiver.c authenticates a staged update
with psa_verify_message() over ECDSA-P256, and there is no P-256 anywhere in
this repo's host build (see the banner in ports/esp32/test/aliro_prim_host.c:
its EC block is a deliberate stand-in, and real curve math runs only in
aliro_prim_psa.c on target). A fake curve would prove nothing.

So the curve runs HERE, once, in python's `cryptography`, over the exact 32
header bytes the suite stages. psafake then replays the result: it accepts that
one (message, signature) pair and refuses every other input, loudly. That
refusal is the check -- it means the receiver really did hand PSA the 32-byte
header and the 64-byte raw r||s signature, and that a single tampered header
byte changes what gets verified.

Nothing here reads the C under test. The header is rebuilt from the on-flash
layout in modules/woz_dfu/include/woz_dfu.h, and the suite asserts that its own
build_head() reproduces these bytes -- so a drift on either side is caught.
"""

import struct
import zlib

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, utils

WOZ_DFU_MAGIC = 0x55464457
WOZ_DFU_ABI_VERSION = 1
WOZ_DFU_HDR_CRC_LEN = 28

# The patch tests/host/test_dfu.c stages: fill_pattern(patch, 70, 3).
PATCH = bytes((3 + i * 7) & 0xFF for i in range(70))


def build_header() -> bytes:
    """struct woz_dfu_hdr for that patch, little-endian, CRC written last."""
    head = struct.pack(
        "<IHHIIIII",
        WOZ_DFU_MAGIC,
        WOZ_DFU_ABI_VERSION,
        0,  # flags
        len(PATCH),  # patch_len
        0,  # to_len
        zlib.crc32(PATCH),  # patch_crc32
        0,  # from_crc32
        0,  # from_len
    )
    assert len(head) == WOZ_DFU_HDR_CRC_LEN, len(head)
    return head + struct.pack("<I", zlib.crc32(head))


def c_array(name: str, data: bytes, indent: str = "\t") -> str:
    rows = []
    for off in range(0, len(data), 8):
        rows.append(indent + ", ".join(f"0x{b:02x}" for b in data[off : off + 8]) + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};"


def main() -> int:
    header = build_header()

    # A fixed private key so the vector is reproducible. It signs nothing that
    # exists outside this file, so it is a test value, not a secret.
    private_key = ec.derive_private_key(
        0x00C0FFEE_1234_5678_9ABC_DEF0_0FED_CBA9_8765_4321_1122_3344_5566_7788_99AA_BBCC
        % ec.SECP256R1().key_size,
        ec.SECP256R1(),
    )
    numbers = private_key.public_key().public_numbers()
    public = b"\x04" + numbers.x.to_bytes(32, "big") + numbers.y.to_bytes(32, "big")

    der = private_key.sign(header, ec.ECDSA(hashes.SHA256()))
    r, s = utils.decode_dss_signature(der)
    raw = r.to_bytes(32, "big") + s.to_bytes(32, "big")

    # Prove the pair verifies before anyone pastes it in.
    private_key.public_key().verify(
        utils.encode_dss_signature(
            int.from_bytes(raw[:32], "big"), int.from_bytes(raw[32:], "big")
        ),
        header,
        ec.ECDSA(hashes.SHA256()),
    )

    print("/* Generated by tests/host/gen_dfu_vector.py -- see that file. */")
    print(c_array("kGoldenPubkey", public))
    print()
    print(c_array("kGoldenHeader", header))
    print()
    print(c_array("kGoldenSignature", raw))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
