/**
 * @file test_matter_pase_sm.c — the PASE responder, driven by a real exchange.
 *
 * K_APPLE_REQ is a real iPhone's PBKDFParamRequest (circuitmatter's recorded
 * packets, payload only). The expected answers come from gen_pase_vector.py,
 * which computes Z and V three independent ways and curve-checks M/N read out
 * of matter_spake2p.c, so the vector is agreement between derivations, not one
 * implementation's opinion. The curve is replayed, not computed (see
 * spakefake.c); everything else -- encoding, context hash, transcript,
 * confirmations, session keys -- runs for real here.
 */
#include <string.h>

#include "matter_pase_sm.h"

#include "spakefake/spakefake.h"
#include "test.h"

/*
 * REAL WIRE BYTES: an iPhone's PBKDFParamRequest. Same capture as
 * test_matter_pase.c, which decodes it field by field; here it is the input
 * that drives the whole state machine.
 */
static const char *const K_APPLE_REQ =
	"15300120a882bce8bfdeab50e04ac596bfc05024db5902b7512ed9b278cfaacc125230122502b6e424030028"
	"0435052501f40125022c012503a00f24041224050b2606000004012407011818";

/* generated by tests/host/gen_pase_vector.py -- do not hand-edit */
static const char *const K_SALT =
	"404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f";
static const char *const K_RESP_RANDOM =
	"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f";
static const char *const K_Y_WS =
	"c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7";
static const char *const K_W0 =
	"c77189dcfabe03801f58373948a6a884db72fdaa93d5262c6828c57a7d766028";
static const char *const K_L =
	"04bbbd9d1e8eb982d8733b84e54dbf6adf943719a1c58bcb55d09dcfb17720709407ead7480fcaea51f9c6a8"
	"0a1e7c62a2c9223a5686445cee6da59a7eb6c06759";
static const char *const K_EXPECT_RESP =
	"15300120a882bce8bfdeab50e04ac596bfc05024db5902b7512ed9b278cfaacc125230123002208081828384"
	"85868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f2503341235042501e80330022040414243"
	"4445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f1818";
static const char *const K_PA =
	"048961ff3ad9ffcc1589abc7798c54d904b842d733b1ee721a49e8faf8ed9b9424caf59cf9842eb0404e23b8"
	"e6d822e35848c42cf437841fdc176cc0f1d9f9d4f0";
static const char *const K_EXPECT_PB =
	"04252597b0cd7f885023b5678f9f710e4ec81ecff6e533b8b5861a7e49d4d03e868d1c539a58de731bce0453"
	"8a36ed21b4009dd8f0cc9a84100c357feb67a2108b";
static const char *const K_Z =
	"04da5b024cfeb107a72f2e378cf44c5ff2fd1034b26c3589091d52ca55f652f2f6ac59e866c9fa3df33beea7"
	"2165ba647e4469ad1f141dc2238e5b8ad4f705dfe9";
static const char *const K_V =
	"049167108bcc98f5ba4601f7eac3922f38929b0b9d63cc5b7d47aeed7f5eb1f694d5df961de3e484aaf4e3a9"
	"9b378beef0ba891f6f9cba71e142a6e3cc1144a82d";
static const char *const K_EXPECT_CB =
	"b8bc9766dd33243beaa77cf24bcfb9ef84c8197491ddf2510235ad78cc50b357";
static const char *const K_CA =
	"6991b9e77290936ba01d5ba67a89f526ec77c3c9d14a1f35856f0b65b6391854";
static const char *const K_EXPECT_I2R = "652b8eab2a3d5713254e3bfed9a60cf0";
static const char *const K_EXPECT_R2I = "87d68b30d3dce7e3cfd27268f1ca4f22";
static const char *const K_EXPECT_ATTEST = "236f3283cda3cb252c93f357792697b4";

/** The iterations the vector was generated with; also PASE's lower bound. */
#define VEC_ITERATIONS 1000u
#define VEC_SESSION_ID 0x1234u

/** StatusReport bodies: general | protocol id | protocol code, all little-endian. */
#define STATUS_SUCCESS "0000000000000000"
#define STATUS_FAILURE "0100000000000200"

struct fixture {
	struct matter_pase_responder r;
	uint8_t out[MATTER_PASE_REPLY_MAX];
	size_t out_len;
	uint8_t opcode;
	uint8_t pa[MATTER_SPAKE_POINT_LEN];
	uint8_t ca[MATTER_SPAKE_HASH_LEN];
};

/**
 * Build the verifier and responder the vector describes, and arm the replay.
 *
 * @return the init return code, so the bad-verifier cases can use this too.
 */
static int setup(struct fixture *f)
{
	struct matter_pase_verifier v;
	uint8_t l[MATTER_SPAKE_POINT_LEN];
	uint8_t rr[MATTER_PASE_RANDOM_LEN];
	uint8_t yws[MATTER_PASE_Y_ENTROPY_LEN];
	uint8_t pb[MATTER_SPAKE_POINT_LEN];
	uint8_t z[MATTER_SPAKE_POINT_LEN];
	uint8_t zv[MATTER_SPAKE_POINT_LEN];

	memset(f, 0, sizeof(*f));
	memset(&v, 0, sizeof(v));

	(void)t_unhex(v.w0, K_W0, sizeof(v.w0));
	(void)t_unhex(l, K_L, sizeof(l));
	memcpy(v.l, l, sizeof(v.l));
	v.salt_len = (uint8_t)t_unhex(v.salt, K_SALT, sizeof(v.salt));
	v.iterations = VEC_ITERATIONS;

	(void)t_unhex(rr, K_RESP_RANDOM, sizeof(rr));
	(void)t_unhex(yws, K_Y_WS, sizeof(yws));
	(void)t_unhex(f->pa, K_PA, sizeof(f->pa));
	(void)t_unhex(f->ca, K_CA, sizeof(f->ca));
	(void)t_unhex(pb, K_EXPECT_PB, sizeof(pb));
	(void)t_unhex(z, K_Z, sizeof(z));
	(void)t_unhex(zv, K_V, sizeof(zv));

	spakefake_replay_arm(v.w0, l, yws, f->pa, pb, z, zv);

	return matter_pase_responder_init(&f->r, &v, VEC_SESSION_ID, rr, yws);
}

/** Feed one message and record what came back. */
static int step(struct fixture *f, uint8_t opcode, const uint8_t *payload, size_t len)
{
	return matter_pase_responder_recv(&f->r, opcode, payload, len, f->out, sizeof(f->out),
					  &f->out_len, &f->opcode);
}

/** Drive the request/response leg, which every later test starts from. */
static int step_request(struct fixture *f, uint8_t *scratch, size_t cap)
{
	long n = t_unhex(scratch, K_APPLE_REQ, cap);

	return step(f, MATTER_PASE_OP_PBKDF_REQ, scratch, (size_t)n);
}

static int all_zero(const uint8_t *b, size_t n)
{
	uint8_t acc = 0u;

	for (size_t i = 0u; i < n; i++) {
		acc |= b[i];
	}
	return acc == 0u;
}

/** Encode a Pake1 carrying @p pa, so the codec builds the peer's message. */
static size_t make_pake1(const uint8_t *pa, uint8_t *buf, size_t cap)
{
	struct matter_pase_pake1 p1;
	size_t n = 0;

	memcpy(p1.pa, pa, MATTER_PASE_POINT_LEN);
	(void)matter_pase_pake1_encode(&p1, buf, cap, &n);
	return n;
}

static size_t make_pake3(const uint8_t *ca, uint8_t *buf, size_t cap)
{
	struct matter_pase_pake3 p3;
	size_t n = 0;

	memcpy(p3.ca, ca, MATTER_PASE_HASH_LEN);
	(void)matter_pase_pake3_encode(&p3, buf, cap, &n);
	return n;
}

void test_matter_pase_sm(void)
{
	struct fixture f;
	uint8_t scratch[256];
	size_t n;

	t_group("StatusReport body");
	{
		uint8_t buf[MATTER_SC_STATUS_LEN];
		size_t len = 0;

		T_EQ("success encodes",
		     matter_sc_status_report(MATTER_SC_CODE_SUCCESS, buf, sizeof(buf), &len),
		     MATTER_OK);
		T_EQ("eight bytes", (long)len, 8L);
		t_vec("success body", buf, len, STATUS_SUCCESS);

		/* The general code is derived from the protocol code rather than
		 * passed in -- PairingSession.h:147-149. */
		T_EQ("failure encodes",
		     matter_sc_status_report(MATTER_SC_CODE_INVALID_PARAM, buf, sizeof(buf), &len),
		     MATTER_OK);
		t_vec("failure body", buf, len, STATUS_FAILURE);

		T_EQ("refuses a short buffer",
		     matter_sc_status_report(MATTER_SC_CODE_SUCCESS, buf, 7u, &len),
		     MATTER_E_NOSPACE);
	}

	t_group("verifier is validated at init");
	{
		struct matter_pase_verifier v;
		struct matter_pase_responder r;
		uint8_t rr[MATTER_PASE_RANDOM_LEN] = {0};
		uint8_t yws[MATTER_PASE_Y_ENTROPY_LEN] = {0};

		memset(&v, 0, sizeof(v));
		v.salt_len = MATTER_PASE_SALT_MAX;
		v.iterations = VEC_ITERATIONS;
		T_EQ("a sound verifier is accepted",
		     matter_pase_responder_init(&r, &v, 1u, rr, yws), MATTER_OK);

		v.salt_len = MATTER_PASE_SALT_MIN - 1u;
		T_EQ("short salt refused", matter_pase_responder_init(&r, &v, 1u, rr, yws),
		     MATTER_E_INVAL);

		v.salt_len = MATTER_PASE_SALT_MAX;
		v.iterations = MATTER_PASE_ITER_MIN - 1u;
		T_EQ("too few iterations refused",
		     matter_pase_responder_init(&r, &v, 1u, rr, yws), MATTER_E_INVAL);

		v.iterations = MATTER_PASE_ITER_MAX + 1u;
		T_EQ("too many iterations refused",
		     matter_pase_responder_init(&r, &v, 1u, rr, yws), MATTER_E_INVAL);

		v.iterations = VEC_ITERATIONS;
		T_EQ("null verifier refused", matter_pase_responder_init(&r, NULL, 1u, rr, yws),
		     MATTER_E_INVAL);
		T_EQ("null entropy refused", matter_pase_responder_init(&r, &v, 1u, rr, NULL),
		     MATTER_E_INVAL);
	}

	t_group("a real iPhone request, all the way to session keys");
	{
		T_EQ("init", setup(&f), MATTER_OK);
		T_EQ("starts idle", matter_pase_responder_state(&f.r), MATTER_PASE_ST_IDLE);

		T_EQ("request accepted", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);
		T_EQ("answers with PBKDFParamResponse", f.opcode, MATTER_PASE_OP_PBKDF_RESP);
		T_EQ("response is 118 bytes", (long)f.out_len, 118L);
		t_vec("response bytes", f.out, f.out_len, K_EXPECT_RESP);
		/* The iPhone's own session id, kept for the secure session that
		 * follows PASE. */
		T_EQ("peer session id", f.r.peer_session_id, 0xE4B6L);
		T_EQ("now waiting for Pake1", matter_pase_responder_state(&f.r),
		     MATTER_PASE_ST_WAIT_PAKE1);

		n = make_pake1(f.pa, scratch, sizeof(scratch));
		T_EQ("Pake1 accepted", step(&f, MATTER_PASE_OP_PAKE1, scratch, n), MATTER_OK);
		T_EQ("answers with Pake2", f.opcode, MATTER_PASE_OP_PAKE2);
		T_EQ("Pake2 is 105 bytes", (long)f.out_len, 105L);
		/* pB at offset 4 and cB at offset 72, past the TLV headers the
		 * codec suite already pins byte for byte. */
		t_vec("pB on the wire", f.out + 4, MATTER_SPAKE_POINT_LEN, K_EXPECT_PB);
		t_vec("cB on the wire", f.out + 72, MATTER_SPAKE_HASH_LEN, K_EXPECT_CB);
		T_EQ("now waiting for Pake3", matter_pase_responder_state(&f.r),
		     MATTER_PASE_ST_WAIT_PAKE3);

		n = make_pake3(f.ca, scratch, sizeof(scratch));
		T_EQ("Pake3 accepted", step(&f, MATTER_PASE_OP_PAKE3, scratch, n), MATTER_OK);
		T_EQ("answers with a StatusReport", f.opcode, MATTER_SC_OP_STATUS_REPORT);
		t_vec("success", f.out, f.out_len, STATUS_SUCCESS);
		T_EQ("done", matter_pase_responder_state(&f.r), MATTER_PASE_ST_DONE);

		t_vec("i2r", f.r.keys.i2r, MATTER_KEY_LEN, K_EXPECT_I2R);
		t_vec("r2i", f.r.keys.r2i, MATTER_KEY_LEN, K_EXPECT_R2I);
		t_vec("attestation challenge", f.r.keys.attestation_challenge, MATTER_KEY_LEN,
		      K_EXPECT_ATTEST);

		/* The replay refuses anything it did not record, so a clean fault
		 * is the assertion that the curve was driven correctly: N to the
		 * key share, M and L to get_ZV, reduce(y_ws) as the scalar. */
		T_OK("no curve call was refused", spakefake_replay_fault() == NULL);
		T_EQ("one key share", (long)spakefake_replay_key_share_calls(), 1L);
		T_EQ("one ZV", (long)spakefake_replay_zv_calls(), 1L);

		T_EQ("nothing is accepted after DONE",
		     step(&f, MATTER_PASE_OP_PBKDF_REQ, scratch, n), MATTER_E_STATE);
		T_EQ("and it answers with a failure report", f.opcode,
		     MATTER_SC_OP_STATUS_REPORT);
		t_vec("failure", f.out, f.out_len, STATUS_FAILURE);
	}

	t_group("a wrong cA does not establish a session");
	{
		uint8_t bad[MATTER_SPAKE_HASH_LEN];

		T_EQ("init", setup(&f), MATTER_OK);
		T_EQ("request", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);
		n = make_pake1(f.pa, scratch, sizeof(scratch));
		T_EQ("Pake1", step(&f, MATTER_PASE_OP_PAKE1, scratch, n), MATTER_OK);

		memcpy(bad, f.ca, sizeof(bad));
		bad[sizeof(bad) - 1u] ^= 0x01u; /* one bit */
		n = make_pake3(bad, scratch, sizeof(scratch));
		T_EQ("refused", step(&f, MATTER_PASE_OP_PAKE3, scratch, n), MATTER_E_TYPE);
		T_EQ("failed", matter_pase_responder_state(&f.r), MATTER_PASE_ST_FAILED);
		T_EQ("still answers the peer", f.opcode, MATTER_SC_OP_STATUS_REPORT);
		t_vec("failure", f.out, f.out_len, STATUS_FAILURE);

		/* A failed PAKE must not leave key material behind for whoever
		 * connects next. */
		T_OK("i2r wiped", all_zero(f.r.keys.i2r, MATTER_KEY_LEN));
		T_OK("r2i wiped", all_zero(f.r.keys.r2i, MATTER_KEY_LEN));
		T_OK("expected cA wiped", all_zero(f.r.expect_ca, MATTER_SPAKE_HASH_LEN));
		T_OK("Ke wiped", all_zero(f.r.ke, MATTER_SPAKE_HALF_LEN));
		T_OK("ephemeral scalar wiped", all_zero(f.r.y, MATTER_SPAKE_SCALAR_LEN));
	}

	t_group("messages out of order end the exchange");
	{
		T_EQ("init", setup(&f), MATTER_OK);
		n = make_pake1(f.pa, scratch, sizeof(scratch));
		T_EQ("Pake1 before the request is refused",
		     step(&f, MATTER_PASE_OP_PAKE1, scratch, n), MATTER_E_STATE);
		T_EQ("failed", matter_pase_responder_state(&f.r), MATTER_PASE_ST_FAILED);
		t_vec("failure", f.out, f.out_len, STATUS_FAILURE);
		T_OK("the curve was never touched", spakefake_replay_key_share_calls() == 0u);

		T_EQ("init", setup(&f), MATTER_OK);
		T_EQ("request", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);
		n = make_pake3(f.ca, scratch, sizeof(scratch));
		T_EQ("Pake3 before Pake1 is refused", step(&f, MATTER_PASE_OP_PAKE3, scratch, n),
		     MATTER_E_STATE);
		T_EQ("failed", matter_pase_responder_state(&f.r), MATTER_PASE_ST_FAILED);

		T_EQ("init", setup(&f), MATTER_OK);
		T_EQ("request", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);
		n = make_pake1(f.pa, scratch, sizeof(scratch));
		T_EQ("Pake1", step(&f, MATTER_PASE_OP_PAKE1, scratch, n), MATTER_OK);
		/* Replaying Pake1 would hand the peer a second transcript against
		 * the same ephemeral scalar. */
		T_EQ("a repeated Pake1 is refused", step(&f, MATTER_PASE_OP_PAKE1, scratch, n),
		     MATTER_E_STATE);
		T_EQ("failed", matter_pase_responder_state(&f.r), MATTER_PASE_ST_FAILED);
	}

	t_group("a malformed pA never reaches the curve");
	{
		uint8_t bad[MATTER_SPAKE_POINT_LEN];

		T_EQ("init", setup(&f), MATTER_OK);
		T_EQ("request", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);

		memcpy(bad, f.pa, sizeof(bad));
		bad[0] = 0x02u; /* compressed marker: no implementation accepts it here */
		n = make_pake1(bad, scratch, sizeof(scratch));
		T_EQ("refused", step(&f, MATTER_PASE_OP_PAKE1, scratch, n), MATTER_E_INVAL);
		T_EQ("failed", matter_pase_responder_state(&f.r), MATTER_PASE_ST_FAILED);
		t_vec("failure", f.out, f.out_len, STATUS_FAILURE);
		T_OK("no key share was computed", spakefake_replay_key_share_calls() == 0u);
	}

	t_group("a caller's short buffer is not the peer's fault");
	{
		uint8_t small[MATTER_PASE_REPLY_MAX - 1u];
		size_t len = 0;
		uint8_t op = 0;
		long reqlen;

		T_EQ("init", setup(&f), MATTER_OK);
		reqlen = t_unhex(scratch, K_APPLE_REQ, sizeof(scratch));
		T_EQ("refused", matter_pase_responder_recv(&f.r, MATTER_PASE_OP_PBKDF_REQ, scratch,
							   (size_t)reqlen, small, sizeof(small),
							   &len, &op),
		     MATTER_E_NOSPACE);
		/* No StatusReport, and crucially no state change: the exchange can
		 * still proceed once the caller supplies a real buffer. */
		T_EQ("nothing emitted", (long)len, 0L);
		T_EQ("still idle", matter_pase_responder_state(&f.r), MATTER_PASE_ST_IDLE);
		T_EQ("and then succeeds", step_request(&f, scratch, sizeof(scratch)), MATTER_OK);
		t_vec("same response", f.out, f.out_len, K_EXPECT_RESP);
	}

	spakefake_replay_clear();
}
