#!/usr/bin/env python3
"""Emit the public half of the MCUboot signing key as a C array.

The application verifies a staged patch's header against this before writing it
to flash, so the key that signs images and the key that authorises updates are
the SAME key. That is the point: one secret to hold, one to rotate, and no way
for the two to drift apart.

Only the public half is emitted. The private key never enters the build output.

    emit_pubkey.py <signing-key.pem> <out.c>
"""

import sys
from pathlib import Path


def main():
    """Read an ECDSA P-256 private key from PEM format, extract its X9.62 uncompressed point public key, and emit it as a C header file for the MCUboot image-signing key."""
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    key_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])

    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("emit_pubkey: needs the 'cryptography' module")

    key = serialization.load_pem_private_key(key_path.read_bytes(), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or key.curve.name != "secp256r1":
        sys.exit(f"emit_pubkey: {key_path} is not an ECDSA P-256 key")

    # X9.62 uncompressed point: 0x04 || X || Y, which is what PSA wants for
    # PSA_KEY_TYPE_ECC_PUBLIC_KEY(PSA_ECC_FAMILY_SECP_R1).
    pub = key.public_key().public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    )
    if len(pub) != 65:
        sys.exit(f"emit_pubkey: expected 65 bytes, got {len(pub)}")

    rows = "\n".join(
        "\t" + " ".join(f"0x{b:02x}," for b in pub[i:i + 8])
        for i in range(0, len(pub), 8)
    )

    out_path.write_text(
        "/* Generated by modules/woz_dfu/scripts/emit_pubkey.py. Do not edit.\n"
        " *\n"
        " * Public half of the MCUboot image-signing key. The application checks a\n"
        " * staged update's header against this before writing it to flash.\n"
        " * X9.62 uncompressed point: 0x04 || X || Y.\n"
        " */\n\n"
        "#include <stdint.h>\n\n"
        "const uint8_t woz_dfu_pubkey[65] = {\n"
        f"{rows}\n"
        "};\n"
    )


if __name__ == "__main__":
    main()
