/* GENERATED by ai/tinyml/gen_model.py -- do not hand-edit.
 * Regenerate with:
 *     ai/tinyml/.venv/bin/python ai/tinyml/gen_model.py
 */

#ifndef WOZ_ML_LOS_SCALER_H
#define WOZ_ML_LOS_SCALER_H

#include "woz_ml_los_features.h"

/* Affine map into the int16 space the tree was trained in:
 *     q = (x - lo) * scale - 16000, rounded half away from zero, clamped.
 * float32 on purpose: gen_model.py proves this agrees with the float64 path
 * sklearn trained through, on every held-out sample.
 *
 * static const, so include this from ONE translation unit. It is in src/ and
 * not in include/ for exactly that reason. */
static const float woz_ml_los_lo[WOZ_ML_LOS_N_FEATURES] = {
	-94.58638f,   /* fp_resid */
	-104.884964f, /* rx_pwr */
};

static const float woz_ml_los_scale[WOZ_ML_LOS_N_FEATURES] = {
	862.199097f, /* fp_resid */
	2427.44238f, /* rx_pwr */
};

#endif /* WOZ_ML_LOS_SCALER_H */
