/* GENERATED by tinyml/linear.py -- do not hand-edit.
 * Regenerate with:
 *     tinyml/.venv/bin/python tinyml/linear.py
 */

#ifndef WOZ_ML_LOS_LIN_H
#define WOZ_ML_LOS_LIN_H

/* Logistic fit with the standardiser folded in, so these multiply the decibels
 * woz_ml_los_features() already produces and no separate scaler is needed. The
 * folding is exact, not an approximation: see tinyml/linear.py. Indices are
 * enum woz_ml_los_feature, so this array is ordered by that enum and not by
 * anything here. */
static const float woz_ml_los_lin_w[WOZ_ML_LOS_N_FEATURES] = {
	-0.174858306f, /* WOZ_ML_LOS_F_FP_RESID */
	-0.400662594f, /* WOZ_ML_LOS_F_RX_PWR */
};

static const float woz_ml_los_lin_bias = -52.466789493f;

#endif /* WOZ_ML_LOS_LIN_H */
