/* GENERATED by tinyml/gen_model.py -- do not hand-edit.
 * Regenerate with:
 *     tinyml/.venv/bin/python tinyml/gen_model.py
 */

// !!! This file is generated using emlearn !!!

#include <stdint.h>

static inline int32_t woz_ml_los_tree_tree_0(const int16_t *features, int32_t features_length)
{
	if (features[0] < 2135) {
		if (features[1] < 3634) {
			return 1;
		} else {
			return 0;
		}
	} else {
		return 0;
	}
}

int32_t woz_ml_los_tree_predict(const int16_t *features, int32_t features_length)
{

	int32_t votes[2] = {
		0,
	};
	int32_t _class = -1;

	_class = woz_ml_los_tree_tree_0(features, features_length);
	votes[_class] += 1;

	int32_t most_voted_class = -1;
	int32_t most_voted_votes = 0;
	for (int32_t i = 0; i < 2; i++) {

		if (votes[i] > most_voted_votes) {
			most_voted_class = i;
			most_voted_votes = votes[i];
		}
	}
	return most_voted_class;
}

int woz_ml_los_tree_predict_proba(const int16_t *features, int32_t features_length, float *out,
				  int out_length)
{

	int32_t _class = -1;

	for (int i = 0; i < out_length; i++) {
		out[i] = 0.0f;
	}

	_class = woz_ml_los_tree_tree_0(features, features_length);
	out[_class] += 1.0f;

	// compute mean
	for (int i = 0; i < out_length; i++) {
		out[i] = out[i] / 1;
	}
	return 0;
}
