/* GENERATED by tinyml/linear.py -- do not hand-edit.
 * Regenerate with:
 *     tinyml/.venv/bin/python tinyml/linear.py
 */

#ifndef WOZ_ML_LOS_LIN_VECTORS_H
#define WOZ_ML_LOS_LIN_VECTORS_H

/* 24 receptions, six per quartile of |margin|, so the confident and the
 * ambiguous are both covered. `confidence` is what woz_ml_los_confidence() must
 * return: the fit evaluated in float32 and made unsigned.
 *
 * Compared with a tolerance rather than for equality, because a host is free to
 * contract the multiply-add into an FMA where the Cortex-M4F does not, and the
 * difference is far below anything a confidence threshold could care about. The
 * gate that matters is above it in the suite: no vector may cross zero. */
struct woz_ml_los_lin_vector {
	float feat[WOZ_ML_LOS_N_FEATURES];
	float confidence;
};

static const struct woz_ml_los_lin_vector woz_ml_los_lin_vectors[] = {
	{ { -65.716409598f, -95.738745084f }, 2.616794586f },
	{ { -73.168534714f, -93.577009877f }, 2.179855347f },
	{ { -65.662172067f, -93.820057371f }, 3.395023346f },
	{ { -69.664802022f, -94.826397243f }, 2.291927338f },
	{ { -66.861161620f, -91.816097287f }, 3.988281250f },
	{ { -68.414754531f, -93.775798633f }, 2.931449890f },
	{ { -76.593528451f, -93.215045435f }, 1.725994110f },
	{ { -79.624684922f, -94.464432801f }, 0.695384979f },
	{ { -91.551147840f, -93.397913024f }, 0.962738037f },
	{ { -84.272929806f, -97.379122294f }, 1.285202026f },
	{ { -63.128845359f, -95.738745084f }, 3.069252014f },
	{ { -86.942511141f, -103.433954267f }, 4.177947998f },
	{ { -79.402513608f, -97.554600780f }, 0.503883362f },
	{ { -81.939224229f, -96.408212981f }, 0.488128662f },
	{ { -84.650705862f, -97.017157853f }, 1.206237793f },
	{ { -89.397277503f, -99.773088277f }, 3.140411377f },
	{ { -75.933939626f, -95.342542515f }, 0.988918304f },
	{ { -72.527606109f, -101.874667653f }, 1.032630920f },
	{ { -72.396322854f, -103.433954267f }, 1.634426117f },
	{ { -83.223130554f, -99.773088277f }, 2.060810089f },
	{ { -81.104731049f, -99.418512937f }, 1.548324585f },
	{ { -84.672784244f, -99.597609791f }, 2.243988037f },
	{ { -85.131433516f, -103.433954267f }, 3.861263275f },
	{ { -76.955198592f, -99.418512937f }, 0.822746277f },
};

#endif /* WOZ_ML_LOS_LIN_VECTORS_H */
