/**
 * @file Generated by scripts/build-size-baseline.ts. Do not hand-edit.
 *
 * The six numbers `/size` prints, extracted from firmware/size-baseline.json
 * rather than bundling that whole file (see build-size-baseline.ts for why).
 * Regenerate with `npm run size-baseline` after `make cdk-size-baseline`
 * updates the source file. size-baseline.test.ts fails if this drifts from a
 * fresh extraction.
 */
import type { SizeBaseline } from "./size-baseline.ts";

export const SIZE_BASELINE: SizeBaseline = {
	"config": "thread+release+smp+lto",
	"commit": "a89799905481f3fc7226868aa0aca6767b471370",
	"board": "decawave_dwm3001cdk",
	"extraConfFile": "overlay-thread.conf;overlay-release.conf;overlay-smp.conf;overlay-lto.conf",
	"regions": {
		"FLASH": {
			"size": 433664,
			"used": 379332,
			"free": 54332,
			"pct": 87.47
		},
		"RAM": {
			"size": 131072,
			"used": 111012,
			"free": 20060,
			"pct": 84.7
		}
	}
};
