/**
 * @file Generated by scripts/build-spec-index.ts. Do not hand-edit.
 *
 * Regenerate with `npm run spec-index` after editing anything in docs/ that
 * cites the Aliro 1.0 specification. spec-index.test.ts fails if this file
 * falls out of sync with a fresh scan of the tree.
 */
import type { SpecCitation } from "../scripts/spec-scan.ts";

export const SPEC_CITATIONS: SpecCitation[] = [
	{
		"section": "11.3.1",
		"file": "docs/ARCHITECTURE.md",
		"line": 860
	},
	{
		"section": "11.7",
		"file": "docs/ARCHITECTURE.md",
		"line": 2265
	},
	{
		"section": "11.9",
		"file": "docs/ARCHITECTURE.md",
		"line": 2271
	},
	{
		"section": "11.3.1",
		"file": "docs/ARCHITECTURE.md",
		"line": 3674
	},
	{
		"section": "Table 8-3",
		"file": "docs/esp32-gotchas.md",
		"line": 254
	},
	{
		"section": "Table 8-9",
		"file": "docs/esp32-gotchas.md",
		"line": 255
	},
	{
		"section": "Table 8-14",
		"file": "docs/esp32-gotchas.md",
		"line": 256
	},
	{
		"section": "8.3.3.5.1",
		"file": "docs/esp32-gotchas.md",
		"line": 256
	},
	{
		"section": "8.3.3.4.3",
		"file": "docs/esp32-gotchas.md",
		"line": 257
	},
	{
		"section": "11.7",
		"file": "docs/esp32-gotchas.md",
		"line": 258
	},
	{
		"section": "Table 11-10",
		"file": "docs/esp32-gotchas.md",
		"line": 258
	},
	{
		"section": "8.3.3.5.1",
		"file": "docs/esp32-gotchas.md",
		"line": 259
	},
	{
		"section": "14",
		"file": "docs/esp32-gotchas.md",
		"line": 270
	},
	{
		"section": "11.7.3.4.1",
		"file": "docs/power-profile.md",
		"line": 8
	}
];
