/* SPDX-License-Identifier: ISC */

/** @file ultrawidelock_uwb_msg_spec.h — UWB ranging-service framing constants. */

#pragma once

#include <stdint.h>

/** Framing: protocol type + message id + 2-byte big-endian payload length. */
#define ULTRAWIDELOCK_HEADER_LENGTH           4
/** Per-attribute framing: attribute id + attribute length. */
#define ULTRAWIDELOCK_ATTRIBUTE_HEADER_LENGTH 2

/** Protocol type field (header byte 0). */
enum ultrawidelock_uwb_message_protocol_type {
	ULTRAWIDELOCK_UWB_PROTOCOL_TYPE_AP = 0x00,
	ULTRAWIDELOCK_UWB_PROTOCOL_TYPE_UWB_RANGING_SERVICE = 0x01,
	ULTRAWIDELOCK_UWB_PROTOCOL_TYPE_NOTIFICATION = 0x02,
	ULTRAWIDELOCK_UWB_PROTOCOL_TYPE_SUPPLEMENTARY_SERVICE = 0x03,
	ULTRAWIDELOCK_UWB_PROTOCOL_TYPE_THIRD_PARTY_APP = 0x04,
};

/** Message id field for the UWB Ranging Service protocol. */
enum ultrawidelock_uwb_message_ranging_service {
	ULTRAWIDELOCK_UWB_MESSAGE_SETUP_M1 = 0x00,
	ULTRAWIDELOCK_UWB_MESSAGE_SETUP_M2 = 0x01,
	ULTRAWIDELOCK_UWB_MESSAGE_SETUP_M3 = 0x02,
	ULTRAWIDELOCK_UWB_MESSAGE_SETUP_M4 = 0x03,
	ULTRAWIDELOCK_UWB_MESSAGE_SUSPEND_REQUEST = 0x04,
	ULTRAWIDELOCK_UWB_MESSAGE_SUSPEND_RESPONSE = 0x05,
	ULTRAWIDELOCK_UWB_MESSAGE_RESUME_REQUEST = 0x06,
	ULTRAWIDELOCK_UWB_MESSAGE_RESUME_RESPONSE = 0x07,
};

/* Ranging-service attribute ids. */
enum ultrawidelock_uwb_ranging_service_attribute {
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_CONFIGURATION_IDENTIFIER = 0x00,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_PULSE_SHAPE_COMBO = 0x01,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SESSION_IDENTIFIER = 0x02,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_CHANNEL_BITMASK = 0x03,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_RAN_MULTIPLIER = 0x04,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SLOT_BITMASK = 0x05,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SYNC_CODE_INDEX_BITMASK = 0x06,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SYNC_CODE_INDEX = 0x07,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_HOPPING_CONFIGURATION_BITMASK = 0x08,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_CHAPS_PER_SLOT = 0x09,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_RESPONDERS_NODES = 0x0A,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_SLOTS_PER_ROUND = 0x0B,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_STS_INDEX0 = 0x0C,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_UWB_TIME0 = 0x0D,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_HOP_MODE_KEY = 0x0E,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_MAC_MODE = 0x0F,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_VENDOR_SPECIFIC = 0x10,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_STATUS = 0x11,
	ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_MAX = 0x12,
};

/* Values of the channel bitmask attribute (id 0x03).
 *
 * In M1 the reader offers a SET, so both bits may be present. In M2 the device
 * must name exactly ONE: a reader compares the byte against these two values and
 * rejects anything else with "unsupported channel bitmask" (ultrawidelock_uwb_msg.c,
 * parse_channel_bitmask), then drops the setup without telling the device.
 *
 * Shared here rather than kept private to ultrawidelock_uwb_msg.c because the side
 * SELECTING a channel and the side VALIDATING that selection must not disagree
 * about which bit means what. */
#define ULTRAWIDELOCK_CHANNEL_BITMASK_CH5 0x01
#define ULTRAWIDELOCK_CHANNEL_BITMASK_CH9 0x02

/** Status attribute values (suspend/resume responses). */
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_STATUS_ACCEPT  0
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_STATUS_REJECT  1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_STATUS_UNKNOWN 0xFF

/** Message id field for the Notification protocol. */
enum ultrawidelock_uwb_message_notification {
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_EVENT = 0x00,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING = 0x01,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_READER_STATUS_CHANGED = 0x02,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_READER_STATUS_AP = 0x03,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_PKE_REQUEST = 0x04,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_INITIATE_AP = 0x05,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_INITIATE_AP_RKE = 0x06,
};

#define ULTRAWIDELOCK_UWB_NOTIFICATION_ATTR_EVENT_BUSY_LENGTH          0
#define ULTRAWIDELOCK_UWB_NOTIFICATION_ATTR_EVENT_GENERAL_ERROR_LENGTH 1

/** Attribute ids inside an Event notification. */
enum ultrawidelock_uwb_message_notification_event_attribute {
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_EVENT_ATTR_BUSY = 0x00,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_EVENT_ATTR_GENERAL_ERROR = 0x01,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_EVENT_ATTR_READER_DESCRIPTOR = 0x02,
};

/** General-error notification codes. */
#define ULTRAWIDELOCK_UWB_NOTIFICATION_GENERAL_ERROR_UNKNOWN              0
#define ULTRAWIDELOCK_UWB_NOTIFICATION_GENERAL_ERROR_RESOURCE_UNAVAILABLE 1
#define ULTRAWIDELOCK_UWB_NOTIFICATION_GENERAL_ERROR_WRONG_PARAMS         2
#define ULTRAWIDELOCK_UWB_NOTIFICATION_GENERAL_ERROR_URSK_UNAVAILABLE     3

/** Attribute ids inside a Ranging notification. */
enum ultrawidelock_uwb_message_notification_ranging_attribute {
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_INIT_RANGING = 0x00,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_INIT_RANGING_RESUME = 0x01,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_INIT_RANGING_SETUP_LATER = 0x02,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_INIT_RANGING_RESUME_LATER = 0x03,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_SECURE_RANGING_FAILED = 0x04,
	ULTRAWIDELOCK_UWB_MESSAGE_NOTIFICATION_RANGING_ATTR_RANGING_SUSPENDED = 0x05,
};

/* Fixed per-attribute value lengths (octets). */
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_CONFIGURATION_IDENTIFIER_LENGTH 2
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_PULSE_SHAPE_COMBO_LENGTH        1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SESSION_IDENTIFIER_LENGTH       4
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_CHANNEL_BITMASK_LENGTH          1

#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_RAN_MULTIPLIER_LENGTH                1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SLOT_BITMASK_LENGTH                  1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SYNC_CODE_INDEX_BITMASK_LENGTH       4
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_SYNC_CODE_INDEX_LENGTH               1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_HOPPING_CONFIGURATION_BITMASK_LENGTH 1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_CHAPS_PER_SLOT_LENGTH         1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_RESPONDERS_NODES_LENGTH       1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_NUMBER_SLOTS_PER_ROUND_LENGTH        1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_STS_INDEX0_LENGTH                    4
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_UWB_TIME0_LENGTH                     8
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_HOP_MODE_KEY_LENGTH                  4
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_MAC_MODE_LENGTH                      1
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_VENDOR_SPECIFIC_OUI_CID_LENGTH       3
#define ULTRAWIDELOCK_UWB_RANGING_SERVICE_ATTR_STATUS_LENGTH                        1
