/* GENERATED by ai/tinyml/gen_model.py -- do not hand-edit.
 * Regenerate with:
 *     ai/tinyml/.venv/bin/python ai/tinyml/gen_model.py
 */

#ifndef WOZ_ML_LOS_FEATURES_H
#define WOZ_ML_LOS_FEATURES_H

#define WOZ_ML_LOS_N_FEATURES 2

/* Feature order is part of the model. A caller that fills the array in a
 * different order gets a confident wrong answer, not an error, because every
 * float is a legal value for every feature. Definitions of what each one
 * means are in ai/tinyml/extract_features.py, which is the only authority. */
enum woz_ml_los_feature {
	WOZ_ML_LOS_F_FP_RESID = 0,
	WOZ_ML_LOS_F_RX_PWR = 1,
};

#endif /* WOZ_ML_LOS_FEATURES_H */
