/* GENERATED by tinyml/gen_model.py -- do not hand-edit.
 * Regenerate with:
 *     tinyml/.venv/bin/python tinyml/gen_model.py
 */

#ifndef ULTRAWIDELOCK_ML_LOG2_TABLE_H
#define ULTRAWIDELOCK_ML_LOG2_TABLE_H

/* log2(1 + i/8) for i in 0..8. The last entry is the interpolation sentinel, so a
 * mantissa in the top bucket has something to interpolate towards. See
 * ultrawidelock_ml_log2.c for why 8 entries is enough. */
#define ULTRAWIDELOCK_ML_LOG2_TABLE_BITS 3

static const float ultrawidelock_ml_log2_tab[9] = {
	0.0f,         0.169925004f, 0.321928084f, 0.459431618f, 0.584962487f,
	0.700439692f, 0.807354927f, 0.906890571f, 1.0f,
};

#endif /* ULTRAWIDELOCK_ML_LOG2_TABLE_H */
