-- Test-request routing: a maintainer asks for a board+iOS pair to be tested,
-- the bot finds owners from `rigs`, and routes it to whoever is awake first.
--
-- `id` is generated by the Worker (crypto.randomUUID()) before the channel
-- post exists, so the Accept button's custom_id can embed it from the
-- start. The row itself is only inserted after the channel post succeeds,
-- with `message_id` already known from that response — so unlike `id`,
-- there is no window where the row exists without it. `thread_id` is the
-- one field that genuinely arrives later (only once someone accepts), so it
-- alone is nullable and filled in by a follow-up UPDATE.
CREATE TABLE IF NOT EXISTS test_requests (
	id             TEXT    PRIMARY KEY,
	requester_id   TEXT    NOT NULL,
	board          TEXT    NOT NULL,
	ios_version    TEXT,
	what           TEXT    NOT NULL,
	-- pending -> claimed -> done. "Claimed" already means someone is running
	-- it in the thread, so there is no separate in-progress state to track;
	-- /test-result (phase 6) is what writes 'done'.
	status         TEXT    NOT NULL DEFAULT 'pending',
	channel_id     TEXT    NOT NULL,
	message_id     TEXT    NOT NULL,
	claimed_by     TEXT,
	thread_id      TEXT,
	escalated_at   INTEGER,
	created_at     INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS test_requests_status ON test_requests (status);

-- Every owner a request matched, awake or not, so the escalation sweep can
-- find "asleep, not yet pinged" candidates without re-running the rigs query
-- (which could have changed since the request was created).
CREATE TABLE IF NOT EXISTS test_request_candidates (
	request_id        TEXT    NOT NULL,
	discord_user_id    TEXT    NOT NULL,
	awake_at_request   INTEGER NOT NULL,
	pinged_awake       INTEGER NOT NULL DEFAULT 0,
	pinged_asleep      INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (request_id, discord_user_id)
);

CREATE INDEX IF NOT EXISTS test_request_candidates_request ON test_request_candidates (request_id);
