#!/usr/bin/env python3
"""Does a linear boundary beat the shipped two-split tree, and can its margin be
the graded confidence the tree cannot give?

Run from the repository root:
    ai/tinyml/.venv/bin/python ai/tinyml/linear.py

WHY ASK. `modules/woz_ml/src/woz_ml_los_tree.h` ships a depth-2 tree: two
comparisons, four leaves. Its generated `woz_ml_los_tree_predict_proba()` writes
1.0f into one slot and 0.0f into the other, because a single tree's leaf IS the
class. So the module can answer "obstructed" and cannot answer "how sure", and
RESULTS.md `Next` item 6 -- wire the classifier to a decision, which has to know
what a wrong answer costs at a door -- has no graded quantity to read. A linear
boundary has one for free: the signed distance from it.

WHAT WOULD MAKE IT SHIPPABLE, all three or none:

1. It has to beat the tree on the same splits. Both are fitted on the same two
   features, so this is a fair fight between decision-boundary shapes: two
   axis-aligned steps against one oblique line.
2. The margin has to be MONOTONE in correctness. A confidence that does not
   predict correctness is a number, not a confidence, and shipping it would be
   worse than shipping nothing.
3. It has to stay libc-free, which `arm-none-eabi-nm -u` checks and `log10f`
   would end. A class decision needs only `w0*x0 + w1*x1 + b > 0`, two multiplies
   on a Cortex-M4F's FPU. The logistic PROBABILITY would need exp(), so it is
   never computed on target: the margin is monotone in the probability, so every
   threshold on one is a threshold on the other, and the exp is a host-side
   convenience that no firmware has to reproduce.

THE SPLIT IS THE BLOCKED CV OF variance.py, not a session hold-out. The tracked
CSV carries no session column, so the honest 0.7729 whole-capture number in
Result 11 cannot be reproduced from this artifact by any script here. Contiguous
blocks stand in. Every model below meets the same folds, so the COMPARISON is
sound even where the absolute level is optimistic.

Self-contained on purpose: variance.py is being edited concurrently for a
different experiment, and importing it would couple this result to that file's
state mid-run. The twenty lines of loader and grouping are duplicated for that
reason and no other.
"""

import csv
import os
import re
import shutil
import subprocess

import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

CSV = "ai/tinyml/captures-door-2026-08-07-ranged.csv"
# Fixed rather than an env knob, for the reason codesize.py gives at the same
# spot: this path and this tool name reach subprocess argv, and taking either
# from the environment is the hole the semgrep gate blocks.
OUTDIR = "ai/tinyml/out-linear"
LIN_H = "modules/woz_ml/src/woz_ml_los_lin.h"
VECTORS_H = "tests/host/data/woz_ml_los_lin_vectors.h"
MODULE_C = "modules/woz_ml/src/woz_ml_lin.c"
BANNER = ("/* GENERATED by ai/tinyml/linear.py -- do not hand-edit.\n"
          " * Regenerate with:\n"
          " *     ai/tinyml/.venv/bin/python ai/tinyml/linear.py\n"
          " */\n")
CC, SIZE, NM = "arm-none-eabi-gcc", "arm-none-eabi-size", "arm-none-eabi-nm"
# Identical to codesize.py: the nRF52833's Cortex-M4F, built the way firmware/
# builds it, CONFIG_SIZE_OPTIMIZATIONS=y being -Os. -ffreestanding because
# Homebrew's arm-none-eabi-gcc ships no C library, which suits a measurement of
# code that must not call into one.
CFLAGS = [
    "-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=hard", "-mfpu=fpv4-sp-d16",
    "-Os", "-ffunction-sections", "-fdata-sections", "-std=c99", "-Wall",
    "-ffreestanding",
]
N_BLOCKS = 8       # contiguous blocks per label, so 16 groups for GroupKFold
SEED = 42
FEATURES = ("fp_resid", "rx_pwr")   # exactly what modules/woz_ml ships on


def load():
    rows = list(csv.DictReader(open(CSV)))
    d = {c: np.array([float(r[c]) for r in rows]) for c in FEATURES}
    d["label"] = np.array([int(r["label"]) for r in rows])
    return d


def blocked_groups(label):
    """Contiguous blocks within each label run, as GroupKFold groups."""
    groups = np.zeros(len(label), dtype=int)
    g = 0
    for L in (0, 1):
        idx = np.flatnonzero(label == L)
        for chunk in np.array_split(idx, N_BLOCKS):
            groups[chunk] = g
            g += 1
    return groups


def linear_model(kind):
    if kind == "logistic":
        return make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000))
    if kind == "svm":
        return make_pipeline(StandardScaler(), LinearSVC(max_iter=20000, dual="auto"))
    return LinearDiscriminantAnalysis()


def out_of_fold(model_fn, X, y, groups):
    """Out-of-fold predictions, and the margin where the model has one.

    Every number in this file is out-of-fold: a margin scored on rows the model
    was fitted on would be confident for the wrong reason.
    """
    preds = np.zeros(len(y))
    margin = np.full(len(y), np.nan)
    for tr, te in GroupKFold(n_splits=8).split(X, y, groups):
        m = model_fn()
        m.fit(X[tr], y[tr])
        preds[te] = m.predict(X[te])
        if hasattr(m, "decision_function"):
            margin[te] = m.decision_function(X[te])
    return preds, margin


def main():
    d = load()
    y = d["label"]
    X = np.column_stack([d[c] for c in FEATURES])
    groups = blocked_groups(y)

    print(f"{len(y)} receptions, {int((y == 0).sum())} clear / {int((y == 1).sum())} obstructed")
    print(f"features {FEATURES}, blocked CV over {2 * N_BLOCKS} contiguous blocks, 8 folds")
    print("absolute level is optimistic (blocks, not sessions); the comparison is not.\n")

    # --- 1. does an oblique line beat two axis-aligned steps? ----------------
    print("%-34s %10s" % ("model", "bAcc"))
    print("-" * 46)
    candidates = (
        ("one threshold on rx_pwr", lambda: DecisionTreeClassifier(max_depth=1, random_state=SEED), [1]),
        ("one threshold on fp_resid", lambda: DecisionTreeClassifier(max_depth=1, random_state=SEED), [0]),
        ("depth-2 tree  <- WHAT SHIPS", lambda: DecisionTreeClassifier(max_depth=2, random_state=SEED), [0, 1]),
        ("depth-4 tree", lambda: DecisionTreeClassifier(max_depth=4, random_state=SEED), [0, 1]),
        ("LDA", lambda: linear_model("lda"), [0, 1]),
        ("linear SVM", lambda: linear_model("svm"), [0, 1]),
        ("logistic regression", lambda: linear_model("logistic"), [0, 1]),
    )
    margins = {}
    for name, fn, cols in candidates:
        p, m = out_of_fold(fn, X[:, cols], y, groups)
        margins[name] = m
        print("%-34s %10.4f" % (name, balanced_accuracy_score(y, p)))

    print("\ncontrol: shuffled label, logistic — %.4f" % balanced_accuracy_score(
        y, out_of_fold(lambda: linear_model("logistic"), X,
                       np.random.RandomState(SEED).permutation(y), groups)[0]))

    # --- 2. is the margin monotone in correctness? --------------------------
    # This is the whole point of the exercise. A confidence that does not track
    # correctness is a number, and a door that trusts it is worse off than one
    # that trusts nothing.
    print("\nmargin vs correctness, logistic, out-of-fold")
    print("%-14s %6s %10s %12s" % ("|margin| bin", "rows", "accuracy", "mean |margin|"))
    print("-" * 46)
    m = margins["logistic regression"]
    p, _ = out_of_fold(lambda: linear_model("logistic"), X, y, groups)
    correct = (p == y)
    am = np.abs(m)
    edges = np.percentile(am, [0, 25, 50, 75, 100])
    for i in range(4):
        sel = (am >= edges[i]) & (am <= edges[i + 1] if i == 3 else am < edges[i + 1])
        print("%-14s %6d %10.4f %12.3f" % (
            f"Q{i + 1}", int(sel.sum()), correct[sel].mean(), am[sel].mean()))

    print("\nthe tree cannot produce this table: a single tree's leaf IS the class,")
    print("so its predict_proba is 1.0/0.0 and every row lands in one bin.")

    # --- 3. the shipped form: raw dB in, no scaler, no libc -----------------
    # Fold the standardiser into the coefficients so the target multiplies the
    # decibels the extractor already hands it. Exact, not an approximation.
    fit = linear_model("logistic").fit(X, y)
    sc, lr = fit[0], fit[1]
    w = lr.coef_[0] / sc.scale_
    b = lr.intercept_[0] - float(np.dot(lr.coef_[0], sc.mean_ / sc.scale_))
    print("\nboundary in physical units, scaler folded in:")
    print("  obstructed  <=>  %+.6f*fp_resid %+.6f*rx_pwr %+.6f  >  0" % (w[0], w[1], b))
    folded = ((X @ w + b) > 0).astype(int)
    print("  folded form vs sklearn on all %d rows: %d disagreements" % (
        len(y), int((folded != fit.predict(X)).sum())))

    # float32 is what the target has; float64 is what this fit is in.
    f32 = ((X.astype(np.float32) @ w.astype(np.float32)
            + np.float32(b)) > 0).astype(int)
    print("  float32 vs float64 on all %d rows:      %d disagreements" % (
        len(y), int((f32 != folded).sum())))
    print("  margin ordering == probability ordering: %s" % (
        bool(np.all(np.argsort(X @ w + b) == np.argsort(fit.predict_proba(X)[:, 1])))))

    hybrid(X, y, groups)
    emit_module(w, b, X, X @ w + b)
    codesize()


def emit_module(w, b, X, margin):
    """Write the coefficients into modules/woz_ml/ and the vectors into the suite.

    Generated rather than copied by hand for the reason gen_model.py gives: a
    constant transcribed once is a constant that drifts silently the next time
    the model is refitted, and nothing downstream can tell.

    THE GATE. float32 is what the target has and float64 is what this fit is in,
    so the header is refused unless every one of the 544 receptions lands on the
    same side of the boundary in both. A confidence that is a hair different on
    target is fine; a class that flips is the model changing when it crosses the
    seam.
    """
    f32 = (X.astype(np.float32) @ w.astype(np.float32) + np.float32(b))
    flips = int(((f32 > 0) != (margin > 0)).sum())
    print("\n\ngate: float32 vs float64 class on all %d rows — %d flips" % (len(X), flips))
    if flips:
        raise SystemExit("REFUSING to write the header: float32 changes %d classes" % flips)

    with open(LIN_H, "w") as f:
        f.write(BANNER + f"""
#ifndef WOZ_ML_LOS_LIN_H
#define WOZ_ML_LOS_LIN_H

/* Logistic fit with the standardiser folded in, so these multiply the decibels
 * woz_ml_los_features() already produces and no separate scaler is needed. The
 * folding is exact, not an approximation: see ai/tinyml/linear.py. Indices are
 * enum woz_ml_los_feature, so this array is ordered by that enum and not by
 * anything here. */
static const float woz_ml_los_lin_w[WOZ_ML_LOS_N_FEATURES] = {{
\t{w[0]:.9f}f, /* WOZ_ML_LOS_F_FP_RESID */
\t{w[1]:.9f}f, /* WOZ_ML_LOS_F_RX_PWR */
}};

static const float woz_ml_los_lin_bias = {b:.9f}f;

#endif /* WOZ_ML_LOS_LIN_H */
""")

    # Six per quartile of |margin|, so the vectors cover the confident and the
    # ambiguous rather than clustering wherever the data happens to be dense.
    am = np.abs(f32.astype(np.float32))
    edges = np.percentile(am, [0, 25, 50, 75, 100])
    rng = np.random.RandomState(SEED)
    pick = []
    for i in range(4):
        sel = np.flatnonzero((am >= edges[i]) &
                             ((am <= edges[i + 1]) if i == 3 else (am < edges[i + 1])))
        pick.extend(rng.choice(sel, size=min(6, len(sel)), replace=False))
    pick = sorted(int(p) for p in pick)

    rows = "\n".join(
        "\t{{ {{ {:.9f}f, {:.9f}f }}, {:.9f}f }},".format(
            X[p, 0], X[p, 1], float(abs(f32[p])))
        for p in pick)
    with open(VECTORS_H, "w") as f:
        f.write(BANNER + f"""
#ifndef WOZ_ML_LOS_LIN_VECTORS_H
#define WOZ_ML_LOS_LIN_VECTORS_H

/* {len(pick)} receptions, six per quartile of |margin|, so the confident and the
 * ambiguous are both covered. `confidence` is what woz_ml_los_confidence() must
 * return: the fit evaluated in float32 and made unsigned.
 *
 * Compared with a tolerance rather than for equality, because a host is free to
 * contract the multiply-add into an FMA where the Cortex-M4F does not, and the
 * difference is far below anything a confidence threshold could care about. The
 * gate that matters is above it in the suite: no vector may cross zero. */
struct woz_ml_los_lin_vector {{
\tfloat feat[WOZ_ML_LOS_N_FEATURES];
\tfloat confidence;
}};

static const struct woz_ml_los_lin_vector woz_ml_los_lin_vectors[] = {{
{rows}
}};

#endif /* WOZ_ML_LOS_LIN_VECTORS_H */
""")
    print("wrote %s and %s (%d vectors)" % (LIN_H, VECTORS_H, len(pick)))


def codesize():
    """Cross-compile the SHIPPED source for the CDK's core and measure it.

    modules/woz_ml/src/woz_ml_lin.c itself, not a copy of it, so the figure
    cannot drift from what a firmware build would link. Same flags, compiler and
    reading as codesize.py, so the number sits beside the tree's without an
    asterisk. Nothing is linked: -ffunction-sections puts each function in its
    own section and --gc-sections can only remove at link time, never add, so
    the per-section object sizes are an upper bound on what a link keeps.
    """
    if not shutil.which(CC):
        print(f"\n\n{CC} not on PATH; skipping the size measurement.")
        return
    os.makedirs(OUTDIR, exist_ok=True)
    obj = os.path.join(OUTDIR, "woz_ml_lin.o")
    subprocess.run([CC, *CFLAGS, "-Imodules/woz_ml/include", "-Imodules/woz_ml/src",
                    "-c", MODULE_C, "-o", obj], check=True)

    out = subprocess.run([SIZE, "-A", obj], capture_output=True, text=True,
                         check=True).stdout
    sizes = {m.group(1): int(m.group(2))
             for m in (re.match(r"^(\.\S+)\s+(\d+)", ln) for ln in out.splitlines())
             if m}
    print("\n\nsize on target, Cortex-M4F at -Os (same flags as codesize.py)")
    print("flags: " + " ".join(CFLAGS))
    total = 0
    for name, n in sorted(sizes.items(), key=lambda kv: -kv[1]):
        if name.startswith((".text", ".rodata", ".data", ".bss")):
            print("  %-34s %5d B" % (name, n))
            total += n
    print("  %-34s %5d B" % ("total", total))

    # The claim the module makes about itself, checked the way its README does.
    und = subprocess.run([NM, "-u", obj], capture_output=True, text=True,
                         check=True).stdout.strip()
    print("  undefined symbols: %s" % (und if und else "none"))


def hybrid(X, y, groups):
    """If the line loses on accuracy, can it still grade the TREE's answers?

    The margin being monotone in the LINEAR model's own correctness is not the
    question a hybrid asks. The tree would still decide; the line would only say
    how sure to be. So the test is whether |margin| predicts the correctness of
    the TREE's prediction, on rows neither model has seen.

    Beside it, the confidence that costs nothing extra: a depth-2 tree has four
    leaves, and each leaf's training-set purity is a per-leaf probability --
    which is exactly what emlearn emits at `leaf_bits=8`, one byte per leaf per
    class. If purity grades as well as the margin does, the two multiplies buy
    nothing and the cheaper answer wins.
    """
    tree_fn = lambda: DecisionTreeClassifier(max_depth=2, random_state=SEED)
    tp = np.zeros(len(y))
    purity = np.zeros(len(y))
    for tr, te in GroupKFold(n_splits=8).split(X, y, groups):
        m = tree_fn().fit(X[tr], y[tr])
        tp[te] = m.predict(X[te])
        counts = m.tree_.value[:, 0, :]                    # per-leaf class counts
        pur = counts.max(axis=1) / counts.sum(axis=1)      # training purity
        purity[te] = pur[m.apply(X[te])]
    _, mg = out_of_fold(lambda: linear_model("logistic"), X, y, groups)
    tree_ok = (tp == y)

    print("\n\ngrading the TREE's answers, out-of-fold (the hybrid question)")
    print("%-22s %6s %14s %10s" % ("bin", "rows", "tree accuracy", "mean conf"))
    print("-" * 56)
    for tag, conf in (("|linear margin|", np.abs(mg)), ("tree leaf purity", purity)):
        edges = np.percentile(conf, [0, 25, 50, 75, 100])
        for i in range(4):
            sel = (conf >= edges[i]) & (conf <= edges[i + 1] if i == 3
                                        else conf < edges[i + 1])
            if sel.sum() == 0:
                continue
            print("%-22s %6d %14.4f %10.3f" % (
                f"{tag} Q{i + 1}", int(sel.sum()), tree_ok[sel].mean(), conf[sel].mean()))
        print()
    print("tree/line disagree on %d of %d rows (%.1f%%)" % (
        int((tp != (mg > 0)).sum()), len(y), 100 * (tp != (mg > 0)).mean()))


if __name__ == "__main__":
    main()
