#!/usr/bin/env bash
# Compile the pinned NCS HCI opcode dispatcher for this port and run it.
#
# The dispatcher is vendor source: it is built straight out of the workspace,
# byte for byte, with no patch step. Everything it needs from Zephyr is
# supplied by ports/freertos-nrf52833/ble/hci_compat, so this script is the
# proof that the port can reach the SoftDevice Controller's opcode-specific
# command API without linking Zephyr.
set -euo pipefail

if [ "$#" -ne 1 ]; then
	printf 'usage: %s <ncs-workspace>\n' "$0" >&2
	exit 2
fi

root=$(cd "$(dirname "$0")/.." && pwd)
workspace=$1
lock="$root/ports/freertos-nrf52833/platform.lock.yml"
controller="$workspace/nrf/subsys/bluetooth/controller"
sdc_include="$workspace/nrfxlib/softdevice_controller/include"
compat="$root/ports/freertos-nrf52833/ble/hci_compat"
stubs="$root/tests/ports/freertos-nrf52833/fake/dispatcher"
out="${ALIRO_BUILD_ROOT:-$root/build}/freertos-nrf52833-host"
gen="$out/stub_sdc_hci_cmd_generated.c"
bin="$out/freertos_hci_dispatcher_test"

expected=$(awk '
	$0 == "ncs_sdk_nrf:" { active = 1; next }
	active && $0 !~ /^ / { exit }
	active && $1 == "revision:" { print $2; exit }
' "$lock")
actual=$(git -C "$workspace/nrf" rev-parse HEAD 2>/dev/null || true)
if [ "$actual" != "$expected" ]; then
	printf 'hci-dispatcher-check: sdk-nrf revision does not match platform.lock.yml\n' >&2
	exit 2
fi
printf '  ok   sdk-nrf revision matches platform.lock.yml\n'

mkdir -p "$out"

# Nothing here rewrites the vendor file, so a re-pin is a plain re-fetch.
if grep -q 'zephyr/' "$controller/hci_internal.c" && \
	[ "$(grep -c '#include <zephyr/' "$controller/hci_internal.c")" -ne 3 ]; then
	printf 'hci-dispatcher-check: the dispatcher gained a Zephyr include the compat layer does not cover\n' >&2
	exit 2
fi

CC=${CC:-cc}
inc=(-I "$compat" -I "$stubs" -I "$sdc_include" -I "$controller")
cfg=(-include "$compat/woz_freertos_hci_config.h")

# The dispatcher is compiled with the port's warnings, unmodified and unpatched.
"$CC" -std=c11 -O1 -Wall -Wextra -Werror -c "${cfg[@]}" "${inc[@]}" \
	"$controller/hci_internal.c" -o "$out/hci_internal.o"
printf '  ok   the pinned opcode dispatcher compiles unmodified and Zephyr-free\n'

# Only the controller commands this configuration actually selects get a stub,
# so the generated file doubles as the record of the linked command surface.
nm -u "$out/hci_internal.o" |
	sed 's/^ *//; s/^_//' |
	grep '^sdc_hci_cmd_' |
	sort -u >"$out/hci_commands.txt"

{
	printf '/* Generated by %s. Do not edit. */\n' "$(basename "$0")"
	printf '#include <stdint.h>\n'
	printf '#include <nrfx.h>\n'
	for header in "$sdc_include"/sdc_hci_cmd_*.h "$sdc_include/sdc_hci_vs.h"; do
		printf '#include <%s>\n' "$(basename "$header")"
	done
	printf '#include "stub_sdc_hci_cmd.h"\n'
	while IFS= read -r symbol; do
		# Prototypes wrap onto a second line when a command both takes
		# and returns parameters, so collect through the semicolon.
		decl=$(awk -v sym="$symbol" '
			index($0, "uint8_t " sym "(") == 1 { collecting = 1 }
			collecting { line = line $0; if (/;/) { print line; exit } }
		' "$sdc_include"/sdc_hci_cmd_*.h "$sdc_include/sdc_hci_vs.h")
		if [ -z "$decl" ]; then
			printf 'hci-dispatcher-check: no prototype for %s\n' "$symbol" >&2
			exit 2
		fi
		printf '%s { return woz_stub_record("%s"); }\n' "${decl%;}" "$symbol"
	done <"$out/hci_commands.txt"
} >"$gen"

count=$(wc -l <"$out/hci_commands.txt" | tr -d ' ')
printf '  ok   the configured command surface is %s controller entry points\n' "$count"

# The stubs ignore their parameters on purpose; that is the only relaxation.
"$CC" -std=c11 -O1 -Wall -Wextra -Werror -Wno-unused-parameter \
	"${cfg[@]}" "${inc[@]}" \
	-I "$root/ports/freertos-nrf52833/include" \
	"$root/tests/ports/freertos-nrf52833/test_hci_dispatcher.c" \
	"$root/ports/freertos-nrf52833/ble/hci_dispatcher_freertos.c" \
	"$stubs/stub_sdc_hci_cmd.c" \
	"$gen" \
	"$out/hci_internal.o" \
	-o "$bin"

"$bin"
printf 'RESULT: PINNED OPCODE DISPATCHER PORTED; board proof remains\n'
