#!/usr/bin/env bash
# Compile the pinned NCS sources this port uses, and run them.
#
# Both are vendor source built straight out of the workspace, byte for byte,
# with no patch step. The HCI opcode dispatcher gets everything it needs from
# Zephyr through ports/freertos-nrf52833/ble/hci_compat, so this is the proof
# that the port reaches the SoftDevice Controller's opcode-specific command API
# without linking Zephyr. The high-precision timer platform needs no
# compatibility layer at all, which is why it is used rather than reimplemented.
set -euo pipefail

if [ "$#" -ne 1 ]; then
	printf 'usage: %s <ncs-workspace>\n' "$0" >&2
	exit 2
fi

root=$(cd "$(dirname "$0")/.." && pwd)
workspace=$1
lock="$root/ports/freertos-nrf52833/platform.lock.yml"
controller="$workspace/nrf/subsys/bluetooth/controller"
sdc_include="$workspace/nrfxlib/softdevice_controller/include"
nrfxlib_802154_include="$workspace/nrfxlib/nrf_802154/sl/include"
compat="$root/ports/freertos-nrf52833/ble/hci_compat"
stubs="$root/tests/ports/freertos-nrf52833/fake/dispatcher"
out="${ALIRO_BUILD_ROOT:-$root/build}/freertos-nrf52833-host"
gen="$out/stub_sdc_hci_cmd_generated.c"
bin="$out/freertos_hci_dispatcher_test"
hp_bin="$out/freertos_hp_timer_test"
hp_timer="$workspace/nrf/modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_hp_timer.c"
ot_radio="$workspace/nrf/modules/openthread/platform/radio_nrf5.c"
ot_compat="$root/ports/freertos-nrf52833/thread/ot_compat"
ot_stubs="$root/tests/ports/freertos-nrf52833/fake/ot_radio"

expected=$(awk '
	$0 == "ncs_sdk_nrf:" { active = 1; next }
	active && $0 !~ /^ / { exit }
	active && $1 == "revision:" { print $2; exit }
' "$lock")
actual=$(git -C "$workspace/nrf" rev-parse HEAD 2>/dev/null || true)
if [ "$actual" != "$expected" ]; then
	printf 'ncs-source-check: sdk-nrf revision does not match platform.lock.yml\n' >&2
	exit 2
fi
printf '  ok   sdk-nrf revision matches platform.lock.yml\n'

mkdir -p "$out"

# Nothing here rewrites the vendor file, so a re-pin is a plain re-fetch.
if grep -q 'zephyr/' "$controller/hci_internal.c" && \
	[ "$(grep -c '#include <zephyr/' "$controller/hci_internal.c")" -ne 3 ]; then
	printf 'ncs-source-check: the dispatcher gained a Zephyr include the compat layer does not cover\n' >&2
	exit 2
fi

CC=${CC:-cc}
inc=(-I "$compat" -I "$root/ports/freertos-nrf52833/include" -I "$stubs" -I "$sdc_include" -I "$controller")
cfg=(-include "$compat/ultrawidelock_freertos_hci_config.h")

# The dispatcher is compiled with the port's warnings, unmodified and unpatched.
"$CC" -std=c11 -O1 -Wall -Wextra -Werror -c "${cfg[@]}" "${inc[@]}" \
	"$controller/hci_internal.c" -o "$out/hci_internal.o"
printf '  ok   the pinned opcode dispatcher compiles unmodified and Zephyr-free\n'

# Only the controller commands this configuration actually selects get a stub,
# so the generated file doubles as the record of the linked command surface.
nm -u "$out/hci_internal.o" |
	sed 's/^ *//; s/^_//' |
	grep '^sdc_hci_cmd_' |
	sort -u >"$out/hci_commands.txt"

{
	printf '/* Generated by %s. Do not edit. */\n' "$(basename "$0")"
	printf '#include <stdint.h>\n'
	printf '#include <nrfx.h>\n'
	for header in "$sdc_include"/sdc_hci_cmd_*.h "$sdc_include/sdc_hci_vs.h"; do
		printf '#include <%s>\n' "$(basename "$header")"
	done
	printf '#include "stub_sdc_hci_cmd.h"\n'
	while IFS= read -r symbol; do
		# Prototypes wrap onto a second line when a command both takes
		# and returns parameters, so collect through the semicolon.
		decl=$(awk -v sym="$symbol" '
			index($0, "uint8_t " sym "(") == 1 { collecting = 1 }
			collecting { line = line $0; if (/;/) { print line; exit } }
		' "$sdc_include"/sdc_hci_cmd_*.h "$sdc_include/sdc_hci_vs.h")
		if [ -z "$decl" ]; then
			printf 'ncs-source-check: no prototype for %s\n' "$symbol" >&2
			exit 2
		fi
		printf '%s { return ultrawidelock_stub_record("%s"); }\n' "${decl%;}" "$symbol"
	done <"$out/hci_commands.txt"
} >"$gen"

count=$(wc -l <"$out/hci_commands.txt" | tr -d ' ')
printf '  ok   the configured command surface is %s controller entry points\n' "$count"

# The stubs ignore their parameters on purpose; that is the only relaxation.
"$CC" -std=c11 -O1 -Wall -Wextra -Werror -Wno-unused-parameter \
	"${cfg[@]}" "${inc[@]}" \
	-I "$root/ports/freertos-nrf52833/include" \
	"$root/tests/ports/freertos-nrf52833/test_hci_dispatcher.c" \
	"$root/ports/freertos-nrf52833/ble/hci_dispatcher_freertos.c" \
	"$stubs/stub_sdc_hci_cmd.c" \
	"$gen" \
	"$out/hci_internal.o" \
	-o "$bin"

"$bin"

# The high-precision timer platform is vendor source with no Zephyr dependency
# at all, so it is compiled as-is against the port's frozen TIMER1 assignment.
if [ ! -f "$hp_timer" ]; then
	printf 'ncs-source-check: high-precision timer platform is missing\n' >&2
	exit 2
fi
if rg -q '#include <zephyr/' "$hp_timer"; then
	printf 'ncs-source-check: the high-precision timer platform gained a Zephyr include\n' >&2
	exit 2
fi
"$CC" -std=c11 -O1 -Wall -Wextra -Werror \
	-I "$stubs" \
	-I "$root/tests/ports/freertos-nrf52833/fake" \
	-I "$nrfxlib_802154_include" \
	"$root/tests/ports/freertos-nrf52833/test_802154_hp_timer.c" \
	"$root/tests/ports/freertos-nrf52833/fake/fake_timer.c" \
	"$hp_timer" \
	-o "$hp_bin"
printf '  ok   the pinned high-precision timer platform compiles unmodified\n'
"$hp_bin"

# The OpenThread radio platform is the whole otPlatRadio implementation, and
# its Zephyr surface is small enough to shim rather than reimplement: one
# semaphore, one intrusive queue, atomics, byte order, logging and assertions.
# Compiling it here is what proves that surface has not grown.
if [ ! -f "$ot_radio" ]; then
	printf 'ncs-source-check: the OpenThread radio platform is missing\n' >&2
	exit 2
fi
for header in zephyr/logging/log.h zephyr/kernel.h zephyr/device.h zephyr/sys/__assert.h \
	zephyr/sys/byteorder.h; do
	if ! rg -Fq "#include <$header>" "$ot_radio"; then
		printf 'ncs-source-check: the radio platform no longer includes %s\n' "$header" >&2
		exit 2
	fi
done
if [ "$(rg -c '#include <zephyr/' "$ot_radio")" -ne 5 ]; then
	printf 'ncs-source-check: the radio platform gained a Zephyr include the shim does not cover\n' >&2
	exit 2
fi
# The shimmed <openthread.h> is empty on purpose. If the platform ever names
# something from Zephyr's OpenThread integration, the shim has to grow with it.
if rg -so 'openthread_[a-z0-9_]+' "$ot_radio" | sort -u |
	rg -sv '^openthread_(802154_callbacks|handle_received_frame|platform_radio_set_eui64|nrf_802154_.*)$' |
	rg -q .; then
	printf 'ncs-source-check: the radio platform now calls into Zephyr OpenThread integration\n' >&2
	exit 2
fi
# -Wno-unused-parameter: three OpenThread callbacks take an instance the Nordic
# platform does not need. The Zephyr build does not enable -Wextra at all.
"$CC" -std=c11 -O1 -Wall -Wextra -Werror -Wno-unused-parameter -fsyntax-only \
	-include "$ot_compat/ultrawidelock_freertos_ot_config.h" \
	-I "$ot_compat" \
	-I "$root/ports/freertos-nrf52833/include" \
	-I "$ot_stubs" \
	-I "$root/tests/ports/freertos-nrf52833/fake" \
	-I "$workspace/modules/lib/openthread/include" \
	-I "$workspace/modules/lib/openthread/examples/platforms" \
	-I "$workspace/nrfxlib/nrf_802154/driver/include" \
	-I "$workspace/nrfxlib/nrf_802154/common/include" \
	-I "$nrfxlib_802154_include" \
	-I "$workspace/nrfxlib/nrf_802154/driver/src" \
	-I "$workspace/nrf/modules/openthread/platform" \
	-DNRF52833_XXAA \
	"$ot_radio"
printf '  ok   the pinned OpenThread radio platform compiles against the port shim\n'

printf 'RESULT: PINNED NCS SOURCES BUILD AND RUN; board proof remains\n'
