/**
 * @file Regenerate src/size-baseline.generated.ts from firmware/size-baseline.json.
 *
 *   npm run size-baseline
 *
 * Importing the full baseline file directly was tried first and rejected: it
 * carries a per-symbol breakdown for every recorded config (3,200+ lines) to
 * answer a question that needs six numbers, and bundling all of it nearly
 * tripled the Worker (62 KiB gzip -> 193 KiB) for data `/size` never reads.
 * This extracts only what `/size` prints, the same way spec-index.ts extracts
 * only citations out of docs/ instead of bundling the prose. `npm run drift`
 * via size-baseline.test.ts fails if this file falls out of sync.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { extractPrimary } from "./size-baseline-extract.ts";

const REPO_ROOT = join(import.meta.dirname, "../..");
const OUT = join(import.meta.dirname, "../src/size-baseline.generated.ts");

const raw = JSON.parse(
	readFileSync(join(REPO_ROOT, "firmware/size-baseline.json"), "utf8"),
);
const extracted = extractPrimary(raw);
if (!extracted) {
	console.error("firmware/size-baseline.json did not have the shape this extractor expects.");
	process.exit(1);
}

const body = `/**
 * @file Generated by scripts/build-size-baseline.ts. Do not hand-edit.
 *
 * The six numbers \`/size\` prints, extracted from firmware/size-baseline.json
 * rather than bundling that whole file (see build-size-baseline.ts for why).
 * Regenerate with \`npm run size-baseline\` after \`make cdk-size-baseline\`
 * updates the source file. size-baseline.test.ts fails if this drifts from a
 * fresh extraction.
 */
import type { SizeBaseline } from "./size-baseline.ts";

export const SIZE_BASELINE: SizeBaseline = ${JSON.stringify(extracted, null, "\t")};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT} (config: ${extracted.config})`);
