/**
 * @file Regenerate src/spec-index.generated.ts from the live docs/ tree.
 *
 *   npm run spec-index
 *
 * Run this after editing anything in docs/ that cites the Aliro 1.0
 * specification. `npm run drift` (via spec-index.test.ts) fails the build if
 * the committed file falls out of sync with a fresh scan, the same way
 * citations.ts is checked against the lines it cites.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { scanDocs } from "./spec-scan.ts";

const REPO_ROOT = join(import.meta.dirname, "../..");
const OUT = join(import.meta.dirname, "../src/spec-index.generated.ts");

const citations = scanDocs(join(REPO_ROOT, "docs"), "docs/");

const body = `/**
 * @file Generated by scripts/build-spec-index.ts. Do not hand-edit.
 *
 * Regenerate with \`npm run spec-index\` after editing anything in docs/ that
 * cites the Aliro 1.0 specification. spec-index.test.ts fails if this file
 * falls out of sync with a fresh scan of the tree.
 */
import type { SpecCitation } from "../scripts/spec-scan.ts";

export const SPEC_CITATIONS: SpecCitation[] = ${JSON.stringify(citations, null, "\t")};
`;

writeFileSync(OUT, body);
console.log(`wrote ${citations.length} citation(s) to ${OUT}`);
