/**
 * @file Regenerates src/assets.generated.ts from the vendored font files and
 * the installed @resvg/resvg-wasm's WASM binary.
 *
 * Both need to reach the Worker as bytes, and need to reach `node --test`
 * as the same bytes with no bundler involved — Wrangler can import `.wasm`
 * and (with a module rule) arbitrary binary files natively, but Node's
 * loader understands neither, and this bot's tests run the TypeScript
 * sources directly. Base64-embedding sidesteps that split entirely: no
 * import rule to keep in sync between environments, no bundler-vs-`node
 * --test` skew. The cost is a large generated file (~1.7 MB gzipped, well
 * under Cloudflare's 3 MB free-tier compressed Worker limit, confirmed
 * against developers.cloudflare.com/workers/platform/limits on 2026-08-04).
 *
 * Run after upgrading @resvg/resvg-wasm or the vendored fonts:
 *   npm run generate-assets
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createRequire } from "node:module";

const ROOT = join(import.meta.dirname, "..");
const require = createRequire(import.meta.url);

function base64Of(path: string): string {
	return readFileSync(path).toString("base64");
}

const resvgWasmPath = require.resolve("@resvg/resvg-wasm/index_bg.wasm");
const resvgPackageJson = join(resvgWasmPath, "../package.json");
const resvgVersion = (JSON.parse(readFileSync(resvgPackageJson, "utf8")) as { version: string }).version;

const interRegular = base64Of(join(ROOT, "assets/fonts/Inter-Regular.ttf"));
const interBold = base64Of(join(ROOT, "assets/fonts/Inter-Bold.ttf"));
const resvgWasm = base64Of(resvgWasmPath);

const out = `/**
 * @file GENERATED by scripts/generate-assets.ts. Do not hand-edit.
 *
 * Inter-Regular.ttf and Inter-Bold.ttf: SIL Open Font License 1.1, fetched
 * from Google Fonts (fonts.gstatic.com, the same static files the Google
 * Fonts CSS API serves) on 2026-08-04. See assets/fonts/NOTICE.
 *
 * index_bg.wasm: from @resvg/resvg-wasm@${resvgVersion} (MPL-2.0), copied
 * at generation time rather than imported, for the reason in
 * scripts/generate-assets.ts's header. Regenerate this file after bumping
 * that dependency so the embedded WASM does not silently drift from
 * package.json's declared version.
 */

export const RESVG_WASM_VERSION = "${resvgVersion}";

export const INTER_REGULAR_TTF_BASE64 = "${interRegular}";

export const INTER_BOLD_TTF_BASE64 = "${interBold}";

export const RESVG_WASM_BASE64 =
	"${resvgWasm}";
`;

writeFileSync(join(ROOT, "src/assets.generated.ts"), out);
console.log(
	`wrote src/assets.generated.ts (fonts ${(interRegular.length / 1024).toFixed(0)}KiB + ${(interBold.length / 1024).toFixed(0)}KiB, wasm ${(resvgWasm.length / 1024).toFixed(0)}KiB, base64)`,
);
